# Generated by Django 5.0.6 on 2025-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': [('can_cancel_publication', 'Can cancel publication'), ('can_edit_description', 'Can edit description'), ('can_change_category', 'Can change category'), ('can_unpublish_product', 'Может отменять публикацию продукта'), ('can_delete_any_product', 'Может удалять любой продукт')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', help_text='Выберите статус публикации продукта', max_length=20, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Дата добавления продукта в каталог', verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Укажите, будет ли продукт опубликован', verbose_name='Маркер публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения продукта', verbose_name='Дата последнего изменения продукта'),
        ),
    ]
